# Generated by Django 5.1.15 on 2026-02-12 17:21

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0000_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ref', models.CharField(db_index=True, help_text='External reference from SFTP', max_length=100, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_contact', 'In Contact'), ('negotiating', 'Negotiating'), ('payment_plan', 'Payment Plan'), ('settled', 'Settled'), ('closed', 'Closed'), ('disputed', 'Disputed')], db_index=True, default='new', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Customizable settings (timezone, currency, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('status_change', 'Status Change'), ('payment', 'Payment'), ('assignment', 'Assignment'), ('import', 'Import')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.agency'),
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('max_accounts', models.IntegerField(default=200, help_text='Simultaneous account limit')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='accounts.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.collector'),
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ref', models.CharField(db_index=True, help_text='External ID from client SFTP', max_length=100, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('ssn_last4', models.CharField(blank=True, default='', help_text='Last 4 digits SSN (encrypted at rest)', max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=2, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='idx_debtor_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.debtor'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['agency', 'status', 'created_at'], name='idx_account_agency_status'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['agency', 'assigned_to'], name='idx_account_agency_collector'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(condition=models.Q(('status__in', ['new', 'assigned'])), fields=['status'], name='idx_account_pending'),
        ),
    ]
