# Generated by Django 5.1.15 on 2026-02-12 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_host', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path_s3', models.CharField(blank=True, help_text='S3 path after upload', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_ok', models.IntegerField(default=0)),
                ('processed_errors', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list, help_text='Error list by line number')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='accounts.agency')),
            ],
            options={
                'verbose_name': 'SFTP Import Job',
                'verbose_name_plural': 'SFTP Import Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'status', 'created_at'], name='idx_import_agency_status')],
            },
        ),
    ]
