environment            = "production"
eks_node_min_size      = 2
eks_node_max_size      = 5
eks_node_desired_size  = 3
eks_node_instance_type = "t3.medium"
db_instance_class      = "db.t3.medium"
cache_node_type        = "cache.t3.micro"
db_allocated_storage   = 50
create_dns             = false
# domain_name          = "debtflow.example.com"  # uncomment when DNS is ready
